preston_ventures:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      database: postgres
      schema: public
  target: dev
